# Generated by Django 3.0.7 on 2023-05-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20230517_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('AIC', 'Aichi'), ('AKT', 'Akita'), ('AMR', 'Aomori'), ('CHB', 'Chiba'), ('EHM', 'Ehime'), ('FKI', 'Fukui'), ('FKO', 'Fukuoka'), ('FSM', 'Fukushima'), ('GFU', 'Gifu'), ('GUM', 'Gunma'), ('HRS', 'Hiroshima'), ('HKD', 'Hokkaido'), ('HYG', 'Hyogo'), ('IBR', 'Ibaraki'), ('IKW', 'Ishikawa'), ('IWT', 'Iwate'), ('KGW', 'Kagawa'), ('KGS', 'Kagoshima'), ('KNG', 'Kanagawa'), ('KCH', 'Kochi'), ('KMM', 'Kumamoto'), ('KYT', 'Kyoto'), ('MIE', 'Mie'), ('MYG', 'Miyagi'), ('MYZ', 'Miyazaki'), ('NGN', 'Nagano'), ('NGS', 'Nagasaki'), ('NRA', 'Nara'), ('NGT', 'Niigata'), ('OTA', 'Oita'), ('OKY', 'Okayama'), ('OKN', 'Okinawa'), ('OSK', 'Osaka'), ('SAG', 'Saga'), ('STM', 'Saitama'), ('SHG', 'Shiga'), ('SMN', 'Shimane'), ('SZK', 'Shizuoka'), ('TOC', 'Tochigi'), ('TKS', 'Tokushima'), ('TKY', 'Tokyo'), ('TTR', 'Tottori'), ('TYM', 'Toyama'), ('WKY', 'Wakayama'), ('YGT', 'Yamagata'), ('YGC', 'Yamaguchi'), ('YNS', 'Yamanashi')], max_length=100),
        ),
    ]
